version: '3.7'
services:
  prometheus:
    image: quay.io/prometheus/prometheus
    ports:
      - '9090:9090'
    volumes:
      - './prometheus/etc/:/etc/prometheus/'

  grafana:
    image: grafana/grafana:master
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=hunter2
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    ports:
      - '3001:3000'
    volumes:
      - './data:/var/lib/grafana'
      - './compiled:/var/lib/grafana/dashboards'
      - './config/dashboards":/etc/grafana/provisioning/dashboards'
      - './config/datasources":/etc/grafana/provisioning/datasources'
